all:
	g++ -o Keno KenoProject.cpp Game.cpp pugixml.cpp BaseObject.cpp BetButton.cpp Bonus.cpp Font.cpp GameKeno.cpp Info.cpp InsertCredit.cpp IntroScreen.cpp NumbersGrid.cpp Outro.cpp Volume.cpp Win.cpp XML.cpp -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lSDL2_gfx
